-
  key: essentials
  title: Wikipedia essentials
  description: |
    To get started, you'll want to introduce your students to the basic rules of writing Wikipedia articles and working with the Wikipedia community.

    As their first Wikipedia assignment milestone, you can ask the students to create user accounts and then complete the online training for students. This training introduces the Wikipedia community and how it works, demonstrates the basics of editing and walks students through their first edits, gives advice for selecting articles and drafting revisions, and explains further sources of support as they continue along. It takes about an hour and ends with a certification step, which you can use to verify that students completed the training.

    Students who complete this training are better prepared to focus on learning outcomes, and spend less time distracted by cleaning up after errors.

    Assignment milestones:
    *Create a user account and enroll on the course page.
    *Complete the online training for students. During this training, you will make edits in a sandbox and learn the basic rules of Wikipedia.
    *To practice editing and communicating on Wikipedia, introduce yourself to any Wikipedians helping your class (such as a Wikipedia Ambassador), and leave a message for a classmate on their user talk page.

    Will completion of the student training be part of your students' grades?
  type: 1  # single choice
  minimum: 1
  options:
    -
      title: Yes, completion of training will be graded.
      output: essentials
      logic: graded_training
    -
      title: No, completion of training will not be graded.
      output: essentials
      logic: ungraded_training

-
  key: early_editing_tasks
  title: Getting started with editing
  description: |
    It is important for students to start editing Wikipedia early on. That way, they become familiar with Wikipedia's markup ("wikisyntax", "wikimarkup", or "wikicode") and the mechanics of editing and communicating on the site. We recommend assigning a few basic Wikipedia tasks early on.
    Which introductory assignments would you like to use to acclimate your students to Wikipedia? You can select none, one, or more. Whichever you select will be added to the assignment timeline.
    For most courses, the '"Critique an article" and "Add to an article" exercises provide a nice foundation for the main writing project.
  type: 0 # multiple choice
  minimum: 0
  options:
    -
      title: Critique an article
      blurb: Critically evaluate an existing Wikipedia article related to the class, and leave suggestions for improving it on the article’s talk page.
      # description:
      logic: critique
    -
      title: Add to an article
      blurb: Using course readings or other relevant secondary sources, add 1–2 sentences of new information to a Wikipedia article related to the class. Be sure to integrate it well into the existing article, and include a citation to the source.
      # description:
      logic: add_to_article
    -
      title: Copyedit an article
      blurb: Browse Wikipedia until you find an article that you would like to improve, and make some edits to improve the language or formatting.
      # description:
      logic: copyedit
    -
      title: Illustrate an article
      blurb: Find an opportunity to improve an article by uploading and adding a photo you took.
      # description:
      logic: illustrate

-
  key: choosing_articles
  title: Choosing articles
  description: |
    Choosing the right (or wrong) articles to work on can make (or break) a Wikipedia writing assignment.

    Some articles may initially look easy to improve, but quality references to expand them may be difficult to find. Finding topics with the right balance between poor Wikipedia coverage and available literature from which to expand that coverage can be tricky. Here are some guidelines to keep in mind when selecting articles for improvement.

    Good choice

    Choose a well-established topic for which a lot of literature is available in its field, but which isn't covered extensively on Wikipedia.

    Gravitate toward "stub" and "start" class articles. These articles often have only 1–2 paragraphs of information and are in need of expansion. Relevant WikiProject pages can provide a list of stubs that need improvement.

    Before creating a new article, search related topics on Wikipedia to make sure your topic isn't already covered elsewhere. Often, an article may exist under another name, or the topic may be covered as a subsection of a broader article.

    Not such a good choice

    Articles that are "not such a good choice" for newcomers usually involve a lack of appropriate research material, highly controversial topics that may already be well developed, broad subjects, or topics for which it is difficult to demonstrate notability.

    * You probably shouldn't try to completely overhaul articles on very broad topics (e.g., Law).
    * You should probably avoid trying to improve articles on topics that are highly controversial (for example, Global Warming, Abortion, or Scientology). You may be more successful starting a sub-article on the topic instead.
    * Don't work on an article that is already of high quality on Wikipedia, unless you discuss a specific plan for improving it with other editors beforehand.
    * Avoid working on something with scarce literature. Wikipedia articles cite secondary literature sources, so it's important to have enough sources for verification and to provide a neutral point of view.
    * Don't start articles with titles that imply an argument or essay-like approach (e.g., The Effects That The Recent Sub-Prime Mortgage Crisis has had on the US and Global Economics). These type of titles, and most likely the content too, may not be appropriate for an encyclopedia.

    As the instructor, you should apply your own expertise to examining Wikipedia’s coverage of your field. You understand the broader intellectual context where individual topics fit in, you can recognize where Wikipedia falls short, you know—or know how to find—the relevant literature, and you know what topics your students should be able to handle. Your guidance on article choice and sourcing is critical for both your students’ success and the improvement of Wikipedia.

    There are two recommended options for selecting articles:
  type: 1 # single choice
  minimum: 1
  options:
    -
      title: Instructor prepares a list
      blurb: You (the instructor) prepare a list of appropriate 'non-existent', 'stub' or 'start' articles ahead of time for the students to choose from.
      description: If possible, you may want to work with an experienced Wikipedian to create the list. Each student chooses an article from the list to work on. Although this requires more preparation, it may help students to start researching and writing their articles sooner.
      logic: choose_article_from_list
    -
      title: Students find articles
      blurb: Each student explores Wikipedia and lists 3–5 topics on their Wikipedia user page that they are interested in for their main project. You (the instructor) should approve article choices before students proceed to writing.
      description: Having students find their own articles provides them with a sense of motivation and ownership over the assignment and exercises their critical thinking skills as they identify content gaps, but it may also lead to choices that are further afield from course material.
      logic: explore_to_find_articles
