-
  key: essentials
  title: Wikipedia Essentials
  description: |
    Learn how to use Wikipedia!
    Your students will learn how to use Wikipedia through a series of assignments.
  type: 1  # Single choice
  minimum: 1
  options:
    -
      title: Include Wiki Essentials
      blurb: Would you like to include Wiki Essentials?
      output: essentials
      selected: true
    -
      title: Don't include Wiki Essentials
      blurb: Would you like to exclude Wiki Essentials?
      description: This is more content about this option
-
  key: drafts
  title: Drafts
  description: Should your students write drafts before publishing?
  type: 1
  minimum: 1
  options:
    -
      title: Write drafts
      blurb: Have your students write drafts of their articles
      description: Additional assignments will be generated instructing your students to write drafts of their work in user space
      logic: drafts
    -
      title: Do not write drafts
      blurb: Your students will write their articles directly into main space
      description: No additional assignments will be generated
-
  key: supplementary
  title: Supplementary Assignments
  description: Practice your Wikipedia skills!
  type: 0  # Multiple choice
  minimum: 0
  options:
    -
      title: Publish an Article
      blurb: Have your students publish a new article to Wikipedia
      description: This is more content about this option
      output: supplementary_publish
    -
      title: Edit an Article
      blurb: Have your students edit an existing article on Wikipedia
      description: This is more content about this option
      output: supplementary_edit