AllCops:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'bin/**/*'

Metrics/MethodLength:
  Max: 20               # Max number of lines in a method
Metrics/AbcSize:
  Max: 40               # Measures method complexity. Would like to lower this.
Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false
Style/ColonMethodCall:
  Enabled: false
Style/NumericLiterals:
  # We should use underscores when the number is meaningful. But when it's
  # an arbitrary number like a user id, underscores are just clutter.
  Enabled: false
Style/AsciiComments:
  Enabled: false # We need non-ascii characters to document Wikipedia stuff.
Performance/ParallelAssignment:
  Enabled: false # We general use this only to initialize empty variables.
