language: ruby
rvm:
  - 2.1.5
  - 2.1.6

before_script:
  - mysql -e '''CREATE DATABASE dashboardtesting
                DEFAULT CHARACTER SET utf8
                DEFAULT COLLATE utf8_general_ci;'''

branches:
  except:
    - course_pages

script: rake spec

