name: 'Sources and Citations'
id: 8
description: |
  How do you find good sources, and cite them on Wikipedia? This tutorial will show you how. 
estimated_ttc: 10 minutes
slides:
  - slug: policies-and-guidelines-basic-overview # 101
  - slug: what-to-expect # 102
