-
  key: essentials
  title: Wikipedia Essentials
  description: Learn how to use Wikipedia!
  type: 1  # Single choice
  minimum: 1
  options:
    -
      title: Include Wiki Essentials
      blurb: Would you like to include Wiki Essentials?
      description: This is more content about this option
      output: essentials
    -
      title: Don't include Wiki Essentials
      blurb: Would you like to exclude Wiki Essentials?
      description: This is more content about this option
-
  key: supplementary
  title: Supplementary Assignments
  description: Practice your Wikipedia skills!
  type: 0  # Multiple choice
  minimum: 0
  options:
    -
      title: Publish an Article
      blurb: Have your students publish a new article to Wikipedia
      description: This is more content about this option
      output: supplementary_publish
    -
      title: Edit an Article
      blurb: Have your students edit an existing article on Wikipedia
      description: This is more content about this option
      output: supplementary_edit