# This file defines the published, accessible
# assignment wizards that are available in the application

# Each key must correspond with the name
# of a config file in the 'assignments' folder

-
  key: researchwrite
  title: Create or expand an article
  blurb: |
    You guide your students to select course-related topics that are not well-covered on Wikipedia, and they work individually or in small teams to develop content — either expanding existing articles or creating new ones.
  description: |
    Students analyze the current gaps, start their research to find high-quality secondary sources, and then consider the best way to organize the available information. Then it's time for them in turn to: propose an outline; draft new articles or new content for existing ones; provide and respond to peer feedback; and move their work into the live article namespace on Wikipedia.

    Along the way, students may work with experienced Wikipedia editors who can offer critical feedback and help make sure articles meet Wikipedia's standards and style conventions, and it's important to incorporate time into the assignment for the students to integrate those suggestions. Students who do great work may have their articles highlighted on Wikipedia's main page, and high quality articles will help inform thousands of future readers about the selected topic.

    Optionally, you may ask your students to write a reflective paper about their Wikipedia experience, present their contributions in class, or develop their own conclusions and arguments in a supplementary essay.
-
  key: translation
  title: Translate an article
  blurb: |
    Students work individually, or in small groups, to translate high-quality articles from the language they are studying's (L2) Wikipedia to their native-language (L1) Wikipedia.
  description: |
    Students gain skills in translation as well as expanding their vocabulary in the language they are studying. Optionally, students fact-check the translated article and seek out sources to support and expand the article in their native-language Wikipedia.
