# This file defines the published, accessible
# assignment wizards that are available in the application

# Each key must correspond with the name
# of a config file in the 'assignments' folder

-
  key: researchwrite
  title: Research and Write
  blurb: Have your students research and write an article in the subject matter of your choice.
  description: This is an in-depth assignment that will take a significant amount of time to complete.
-
  key: translation
  title: Translation
  blurb: Have your students research and write an article in the subject matter of your choice.
  description: This assignment will reinforce previously-established skills in your students.