# Add configuration values here
#
# Fulfill value requirements and save as application.yml
#
# Values required for WikiEduDashboard include:
#   wikipedia_username: <your Wikipedia username>
#   wikipedia_password: <your Wikipedia password>
#
#   cohorts: "<cohort_1>,<cohort_2>"
#   cohort_<cohort_1>: "Wikipedia:Education_program/Dashboard/Fall_2014_course_ids"
#   cohort_<cohort_2>: "Wikipedia:Education_program/Dashboard/course_ids"