dashboard_title: Wiki Education Foundation Dashboard
dashboard_url: dashboard.wikiedu.org
wiki_language: en

wikipedia_token: c8d71767a8a3463bb421f9a67b9e1410
wikipedia_secret: e020ade9f11170869f121586a8cdaf84817cc378
oauth_ids: '218,306'

course_prefix: "Wikipedia:Wiki_Ed"
course_announcement_page: 'Wikipedia:Education_noticeboard'


sentry_dsn: 'https://6ba168c8d90342f99e6a36a6c0e3e21f:b427238d3282406382db7dff4eb6af52@app.getsentry.com/68584'
sentry_public_dsn: 'https://6ba168c8d90342f99e6a36a6c0e3e21f@app.getsentry.com/68584'

course_id_list: "Wikipedia:Education_program/Dashboard/course_ids"

cohorts: "Year_of_Science,New_York_City,Society_for_Marine_Mammalogy,American_Sociological_Association,National_Women's_Studies_Association,Association_for_Psychological_Science,Midwest_Political_Science_Association,American_Society_of_Plant_Biologists,Louisiana_State_University,spring_2016,fall_2014,visiting_scholars,summer_2015,Student_Groups_Pilot,spring_2015,fall_2015,2015_summer_seminar"

cohort_summer_2015: "Wikipedia:Education_program/Dashboard/Summer_2015_course_ids"
cohort_Student_Groups_Pilot: "Wikipedia:Education_program/Dashboard/Student_Groups_Pilot"
cohort_spring_2015: "Wikipedia:Education_program/Dashboard/course_ids"
cohort_fall_2014: "Wikipedia:Education_program/Dashboard/Fall_2014_course_ids"

default_cohort: "fall_2015"
update_length: "30"
cron_log_debug: "true"

logo_file: "wiki-logo.png"
favicon_file: favicon.ico"
favicon_dev_file: "favicon_dev.png"
