# Add configuration values here
#
# Fulfill value requirements and save as application.yml
# 
# Values required for WikiEduDashboard include:
#   wikipedia_username: <your Wikipedia username>
#   wikipedia_password: <your Wikipedia password>
#   course_id_list: "Wikipedia:Education_program/Dashboard/course_ids"
