# Add configuration values here.
#
# Fulfill value requirements and save as application.yml
#
# Values required for WikiEduDashboard include:

# A Wikipedia username and password. This is used for making API calls.
# You can (and probably should) make an account just to use for this purpose.
  wikipedia_username: <Wikipedia username>
  wikipedia_password: <Wikipedia password>

# Wikimedia OAuth consumer details. Register a consumer at:
# https://www.mediawiki.org/wiki/Special:OAuthConsumerRegistration/propose
# No one but the user who registers the consumer will be able to log in until
# the consumer gets approved by Wikimedia Foundation staff.
  wikipedia_token: <consumer token>
  wikipedia_secret: <secret token>

# The language version of Wikipedia: <wiki_language>.wikipedia.org
  wiki_language: en

# To set up error logging via Sentry, add a Sentry project url here:
  sentry_dsn: 'http://somelongkey:anotherlongkey@sentry.myserver.com/1'

# One or more cohorts of classes, with each cohort defined by a wiki page of
# course ids, one per line. For development, list at least 2 cohorts,
# which are needed for integration tests.
#
# Cohort names become uppercase, and underscores become spaces.
  cohorts: "fall_2014,spring_2015"

  cohort_fall_2014: "Wikipedia:Education_program/Dashboard/Fall_2014_course_ids"
  cohort_spring_2015: "Wikipedia:Education_program/Dashboard/course_ids"

# The slug for the default cohort
  default_cohort: "student_groups"

# How many days after a course ends should the dashboard continue updating
# data for it?
  update_length: "30"

# Set to true to use log level 'debug' for update logs. The default is 'info'.
  cron_log_debug: false
  
# Uncomment no_views to disable view stats updates.
# no_views: "true"
