# Add configuration values here.
#
# Fulfill value requirements and save as application.yml
#
# Values required for WikiEduDashboard include:

# A Wikipedia username and password. This is used for making API calls.
# You can (and probably should) make an account just to use for this purpose.
  wikipedia_username: <Wikipedia username>
  wikipedia_password: <Wikipedia password>

# Wikimedia OAuth consumer details. Register a consumer at:
# https://www.mediawiki.org/wiki/Special:OAuthConsumerRegistration/propose
# No one but the user who registers the consumer will be able to log in until
# the consumer gets approved by Wikimedia Foundation staff.
  wikipedia_token: <consumer token>
  wikipedia_secret: <secret token>

# The language version of Wikipedia: <wiki_language>.wikipedia.org
  wiki_language: en

# The prefix for all course pages that get posted on behalf of users.
# This should probably be in the Project (Wikipedia) namespace, and should be
# a prefix that will only be used for this purpose.
  course_prefix: 'Wikipedia:Wiki_Ed'
  course_talk_prefix: 'Wikipedia_talk:Wiki_Ed'

# This is the community discussion page where new courses should be announced.
  course_announcement_page: 'Wikipedia:Education_noticeboard'

# Setting disable_wiki_output to 'true' means course pages will not be mirrored
# to the wiki.
  disable_wiki_output: 'false'

# Comma-separated list of OAuth client IDs used by the system for Wiki edits
  oauth_ids: '252,212'

# To set up error logging via Sentry, add a Sentry project url here:
  sentry_dsn: 'http://somelongkey:anotherlongkey@sentry.myserver.com/1'

# One or more cohorts of classes, with each cohort defined by a wiki page of
# course ids, one per line. For development, list at least 2 cohorts,
# which are needed for integration tests.
#
# Cohort names become uppercase, and underscores become spaces.
  cohorts: "fall_2014,spring_2015"

  cohort_fall_2014: "Wikipedia:Education_program/Dashboard/Fall_2014_course_ids"
  cohort_spring_2015: "Wikipedia:Education_program/Dashboard/course_ids"

# The slug for the default cohort
  default_cohort: "student_groups"

# How many days after a course ends should the dashboard continue updating
# data for it?
  update_length: "30"

# Uncomment cron_log_debug to use log level 'debug' for update logs. The default is 'info'.
#  cron_log_debug: "true"

# Uncomment no_views to disable view stats updates.
# no_views: "true"
